#Gustavo Kley
### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/produto/2 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json

{
    "nome" : "Motor Elétrico",
    "descricao" : "Motor Elétrico 100HP",
    "preco" : 15.50,
    "quantidade" : 10,
    "categoria" : "Máquinas",
    "foto" : "foto.jpg",
    "disponivel" : false,
    "estoque" : 10,
    "fornecedor" : "WEG"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1
content-type: application/json

{
    "nome" : "Motor Elétrico",
    "descricao" : "Motor Elétrico 10HP",
    "preco" : 15.50,
    "quantidade" : 10,
    "categoria" : "Máquinas",
    "foto" : "foto.jpg",
    "disponivel" : false,
    "estoque" : 10,
    "fornecedor" : "WEG"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/2 HTTP/1.1